"""add titular to cuentas

Revision ID: 088604e8f5db
Revises: 2eecd326e344
Create Date: 2026-09-19 00:28:54.414671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '088604e8f5db'
down_revision: Union[str, Sequence[str], None] = '2eecd326e344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas', sa.Column('titular', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas', 'titular')
    # ### end Alembic commands ###
