"""add color to notas

Revision ID: 0f1b21169cbe
Revises: 487d8301ce79
Create Date: 2026-09-22 01:41:08.971582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1b21169cbe'
down_revision: Union[str, Sequence[str], None] = '487d8301ce79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('color', sa.String(length=20), nullable=False, server_default='rosa'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'color')
    # ### end Alembic commands ###
