"""add transacciones recurrentes

Revision ID: 22472dcee729
Revises: 0f1b21169cbe
Create Date: 2026-09-22 22:50:28.090207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22472dcee729'
down_revision: Union[str, Sequence[str], None] = '0f1b21169cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacciones_recurrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('tarjeta_id', sa.Integer(), nullable=True),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('frecuencia', sa.String(length=20), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activa', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas.id'], ),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjetas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacciones_recurrentes_id'), 'transacciones_recurrentes', ['id'], unique=False)
    op.create_table('recurrentes_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurrente_id', sa.Integer(), nullable=False),
    sa.Column('dia_del_mes', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('etiqueta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recurrente_id'], ['transacciones_recurrentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurrentes_pagos_id'), 'recurrentes_pagos', ['id'], unique=False)
    op.create_table('registros_recurrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurrente_id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('fecha_procesado', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ingreso_id', sa.Integer(), nullable=True),
    sa.Column('gasto_id', sa.Integer(), nullable=True),
    sa.Column('egreso_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos_cuenta.id'], ),
    sa.ForeignKeyConstraint(['gasto_id'], ['gastos.id'], ),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['recurrentes_pagos.id'], ),
    sa.ForeignKeyConstraint(['recurrente_id'], ['transacciones_recurrentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_recurrentes_id'), 'registros_recurrentes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_recurrentes_id'), table_name='registros_recurrentes')
    op.drop_table('registros_recurrentes')
    op.drop_index(op.f('ix_recurrentes_pagos_id'), table_name='recurrentes_pagos')
    op.drop_table('recurrentes_pagos')
    op.drop_index(op.f('ix_transacciones_recurrentes_id'), table_name='transacciones_recurrentes')
    op.drop_table('transacciones_recurrentes')
    # ### end Alembic commands ###
