"""add dia_pago to tarjetas

Revision ID: 2eecd326e344
Revises: bffc7ee6a8d3
Create Date: 2026-09-18 23:24:03.250878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eecd326e344'
down_revision: Union[str, Sequence[str], None] = 'bffc7ee6a8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarjetas', sa.Column('dia_pago', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarjetas', 'dia_pago')
    # ### end Alembic commands ###
