"""add cuenta_id to tarjetas

Revision ID: 487d8301ce79
Revises: 4f4d54eec08f
Create Date: 2026-09-22 01:10:51.603641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487d8301ce79'
down_revision: Union[str, Sequence[str], None] = '4f4d54eec08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarjetas', sa.Column('cuenta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tarjetas', 'cuentas', ['cuenta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarjetas', type_='foreignkey')
    op.drop_column('tarjetas', 'cuenta_id')
    # ### end Alembic commands ###
