"""add tipo to tarjetas, make corte y pago nullable

Revision ID: 4f4d54eec08f
Revises: 5f952c2b7603
Create Date: 2026-09-22 00:28:46.926594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4d54eec08f'
down_revision: Union[str, Sequence[str], None] = '5f952c2b7603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarjetas', sa.Column('tipo', sa.String(length=10), nullable=False, server_default='credito'))
    op.alter_column('tarjetas', 'dia_corte',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarjetas', 'dia_corte',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tarjetas', 'tipo')
    # ### end Alembic commands ###
