"""add cuenta_id to abonos_deuda

Revision ID: 736dbfe8fa34
Revises: 65864f982863
Create Date: 2026-09-21 23:47:23.328964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736dbfe8fa34'
down_revision: Union[str, Sequence[str], None] = '65864f982863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonos_deuda', sa.Column('cuenta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'abonos_deuda', 'cuentas', ['cuenta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'abonos_deuda', type_='foreignkey')
    op.drop_column('abonos_deuda', 'cuenta_id')
    # ### end Alembic commands ###
