"""add notas table

Revision ID: 7ce79f8fcbd9
Revises: 996db6251681
Create Date: 2026-09-18 00:09:49.089772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce79f8fcbd9'
down_revision: Union[str, Sequence[str], None] = '996db6251681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_id'), 'notas', ['id'], unique=False)
    op.alter_column('tarjetas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'tarjetas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarjetas', type_='foreignkey')
    op.alter_column('tarjetas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_notas_id'), table_name='notas')
    op.drop_table('notas')
    # ### end Alembic commands ###
