"""add numero_cuenta to cuentas

Revision ID: bffc7ee6a8d3
Revises: f577feb2911f
Create Date: 2026-09-18 00:49:21.383742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffc7ee6a8d3'
down_revision: Union[str, Sequence[str], None] = 'f577feb2911f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
