"""agregar categoria a gastos

Revision ID: c05b619dfc74
Revises: 6dd5addc2d36
Create Date: 2026-09-11 02:22:59.430147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05b619dfc74'
down_revision: Union[str, Sequence[str], None] = '6dd5addc2d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('categoria', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gastos', 'categoria')
    # ### end Alembic commands ###
