"""add numero_cuenta to cuentas

Revision ID: f577feb2911f
Revises: 7ce79f8fcbd9
Create Date: 2026-09-18 00:40:05.046204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f577feb2911f'
down_revision: Union[str, Sequence[str], None] = '7ce79f8fcbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cuentas', sa.Column('numero_cuenta', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cuentas', 'numero_cuenta')
    # ### end Alembic commands ###
